<?php
/**
 * Description of language_es.php
 * array con todas las palabras y sus
 * traducciones
 *
 * @author Raúl
 */
$texts = array(
	'About us' => 'Sobre nosotros',
	'What we do?' => '¿Qué hacemos?',
	'Where we are?' => '¿Dóde estamos?',
	'Contact' => 'Contacto',
	'Login' => 'Inicio Sesión',
	'WELCOME'=> 'BIENVENIDO',
	'E-mail:' => 'Correo Electronico:',
	'Password:' => 'Contraseña',
	'¿You forgot the password?' => 'Has olvidado la contraseña?',
	'Accept' => 'Aceptar',
	'Register' => 'Registrar',
	'Time Bank' => 'Banco de Tiempo',
	'Guest' => 'Invitado',
	'Index' => 'Inicio',
	'Selects a category' => 'Selecciona una categoría',
	'Category' => 'Categoría',
	'Options' => 'Opciones',
	'My Offers' => 'Mis Ofertas',
	'My Demands' => 'Mis Demandas',
	'Rate' => 'Valorar',
	'Notifications' => 'Notificaciones',
	'Profile' => 'Perfil',
	'Management category' => 'Gestión de categorías',
	'User management' => 'Gestión de usuarios',
	'Delete deals' => 'Eliminar ofertas',
	'Exit' => 'Salir',
	'Popular Offers' => 'Ofertas populares',
	'Title offer' => 'Título Oferta',
	'Category' => 'Categoria',
	'Something more' => 'Algo mas',
	'Create offer' => 'Crear oferta',
	'Back' => 'Volver',
	'My offer' => 'Mi oferta',
	'User Panel' => 'Panel de usuario',
	'My offers' => 'Mis ofertas',
	'Add offer' => 'Añadir oferta',
	'Name' => 'Nombre',
	'Schedule' => 'Horario',
	'Description' => 'Descripción',
	'Reset' => 'Borrar campos',
	'Create' => 'Crear',
	'Demand' => 'Demanda',
	'Applicant' => 'Solicitante',
	'View' => 'Ver',
	'View demand' => 'Ver demanda',
	'Offer' => 'Oferta',
	'Reject' => 'Rechazar',
	'You might be interested any of their offers' => 'Quizá te interese alguna de sus ofertas',
	'History' => 'Historial',
	'Name of the offer' => 'Nombre de la oferta',
	'Person' => 'Persona',
	'Valuation' => 'Valoración',
	'Score' => 'Puntuación',
	'Opinion' => 'Opinión',
	'Notification' => 'Notificación',
	'Notifications' => 'Notificaciones',
	'Status' => 'Estado',
	'Bidder' => 'Ofertante',
	'Contact' => 'Contacto',
	'Phone' => 'Telefono',
	'Offered hours' => 'Horas ofertadas',
	'Hours defendants' => 'Horas demandadas',
	'Rating' => 'Valoraciones',
	'Modify' => 'Modificar',
	'Profile modify' => 'Modificar perfil',
	'Repeat password' => 'Repetir contraseña',
	'Modify category' => 'Modificar categoria',
	'Save' => 'Guardar',
	'Remove' => 'Eliminar',
	'New' => 'Nueva',
	'Add category' => 'Agregar categoria',
	'Users management' => 'Gestion de usuarios',
	'User remove' => 'Usuario eliminado',
	'Remove offer' => 'Eliminar oferta',
	'Offerid...' => 'IDoferta...',
	'Search' => 'Buscar',
	'Offers View' => 'Ver Ofertas',
	'Are you sure to remove this offer?' => '¿Estás seguro de que quieres eliminar esta oferta?',
	'Yes' => 'Sí',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	
	
	'Administrator Panel' => 'Panel Administrador'
);
?>
